%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\OperaDownload\Laboratorio Electronica\lab-electronica\TP2\1.Datos\LC.xlsx
%    Worksheet: Sheet2
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/09/28 13:29:48

%% Import the data
[~, ~, raw] = xlsread('E:\OperaDownload\Laboratorio Electronica\lab-electronica\TP2\1.Datos\LC.xlsx','Sheet2','A2:H32');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
LCS1 = table;

%% Allocate imported array to column variable names
LCS1.Cs = data(:,1);
LCS1.Modulo = data(:,2);
LCS1.Fasegrado = data(:,3);
LCS1.R = data(:,4);
LCS1.L = data(:,5);
LCS1.C = data(:,6);
LCS1.Q = data(:,7);
LCS1.D = data(:,8);

%% Clear temporary variables
clearvars data raw R;

Rs= 1;
Rl=5e6;
L=38e-9;
C= 8.2e-9;

% s = tf('s');
s = tf('s');
% H = 1/(s*C*R+1);
f1 = 10: 200 : 10e6;
H =  (s^2*L*C*Rl+s*(L+C*Rl*Rs)+Rl+Rs)/(s*C*Rl+1);
% ZR = Rs + (s*L)^2*Rp/((Rp-s^2*C*Rp*L)^2+(s*L)^2)

[magn, phase] = bode(H,2*pi*f1);
magn = squeeze (magn);
phase = squeeze(phase);
Hdb = 20*log10(magn);

% [magn, phase] = bode(ZR,2*pi*f1);
% magn = squeeze (magn);
% phase = squeeze(phase);



figure
semilogx(LCS1.Cs, (LCS1.Fasegrado))
hold on
semilogx(f1, phase);
title('Bode de Fase');
xlabel('frecuencia[Hz]');
ylabel('Fase [Grados]');
grid on
legend('Medido','Teórico');
hold off

figure
semilogx(LCS1.Cs, 20*log10(LCS1.Modulo))
hold on
semilogx(f1, Hdb);
title('Bode de Magnitud');
xlabel('frecuencia[Hz]');
ylabel('magnitud[dB]');
grid on
legend('Medido','Teórico');
hold off
