%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\OperaDownload\Laboratorio Electronica\lab-electronica\TP2\1.Datos\LC.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/09/28 11:53:25

%% Import the data
[~, ~, raw] = xlsread('E:\OperaDownload\Laboratorio Electronica\lab-electronica\TP2\1.Datos\LC.xlsx','Sheet1','A2:H45');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
LC = table;

%% Allocate imported array to column variable names
LC.Ls = data(:,1);
LC.Modulo = data(:,2);
LC.Fasegrado = data(:,3);
LC.R = data(:,4);
LC.L = data(:,5);
LC.C = data(:,6);
LC.Q = data(:,7);
LC.D = data(:,8);

%% Clear temporary variables
clearvars data raw;


Rs= 1;
Rl=5e6;
L=38e-9;
C= 8.2e-9;

% s = tf('s');
s = tf('s');
% H = 1/(s*C*R+1);
f1 = 10: 200 : 10e6;
H =  (s^2*L*C*Rl+s*(L+C*Rl*Rs)+Rl+Rs)/(s*C*Rl+1);
% ZR = Rs + (s*L)^2*Rp/((Rp-s^2*C*Rp*L)^2+(s*L)^2)

% [magn, phase] = bode(H,2*pi*f1);
% magn = squeeze (magn);
% phase = squeeze(phase);
% Hdb = 20*log10(magn);

% [magn, phase] = bode(ZR,2*pi*f1);
% magn = squeeze (magn);
% phase = squeeze(phase);



figure
semilogx(LC.Ls, log10LC.R)
hold on
semilogx(f1, magn);
title('Bode de Magnitud');
xlabel('frecuencia[Hz]');
ylabel('impedancia [ohms]');
grid on
legend('Medido','Teórico');
hold off

% figure
% semilogx(LC.Ls, 20*log10(LC.Modulo))
% hold on
% semilogx(f1, Hdb);
% title('Bode de Magnitud');
% xlabel('frecuencia[Hz]');
% ylabel('magnitud[dB]');
% grid on
% legend('Medido','Teórico');
% hold off
