%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\OperaDownload\Laboratorio Electronica\lab-electronica\TP2\2.Datos\2.c.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/09/25 22:08:38

%% Import the data
[~, ~, raw] = xlsread('E:\OperaDownload\Laboratorio Electronica\lab-electronica\TP2\2.Datos\2.c.xlsx','Sheet1','A2:E39');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
TP2C = table;

%% Allocate imported array to column variable names
TP2C.freq = data(:,1);
TP2C.vin = data(:,2);
TP2C.vout = data(:,3);
TP2C.fase = data(:,4);
TP2C.mag = data(:,5);

%% Clear temporary variables
clearvars data raw;

R= 130;
C= 8.2e-9;
L= 1e-3;
s = tf('s');
H = 1/((s^2*C*L+s*C*R+1));
f1 = 5.5e3: 200 : 20*(55e3);
[magn, phase] = bode(H,2*pi*f1);
magn = squeeze (magn);
phase = squeeze(phase);
Hdb = 20*log10(magn);
% semilogx(f1, phase);
% semilogx(f1, Hdb);



figure
semilogx(TP2C.freq, TP2C.fase)
hold on
semilogx(f1, phase);
grid on
title('Bode de Fase');
xlabel('frecuencia[Hz]');
ylabel('fase [grados]');
hold off

figure
semilogx(TP2C.freq, TP2C.mag)
hold on
semilogx(f1, Hdb);
grid on
title('Bode de Magnitud');
xlabel('frecuencia[Hz]');
ylabel('magnitud[dB]');
hold off


